export const metadata = {
  title: 'Stories App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-screen">
      <body className="h-screen flex flex-col">
        <div className="h-full flex overflow-auto">
          {children}
        </div>
      </body>
    </html>
  )
}